version: '3.8'

services:
  # Media Server - Jellyfin
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - ${CONFIG_DIR}/jellyfin:/config
      - ${TV_DIR}:/media/tv:ro
      - ${MOVIES_DIR}:/media/movies:ro
      - ${MOVIES_OVERFLOW_DIR}:/media/movies_overflow:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - media_network

  # Download Client - qBittorrent
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${TV_DIR}:/media/tv
      - ${MOVIES_DIR}:/media/movies
      - ${MOVIES_OVERFLOW_DIR}:/media/movies_overflow
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    networks:
      - media_network

  # TV Show Management - Sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${TV_DIR}:/media/tv
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - media_network

  # Movie Management - Radarr
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${MOVIES_DIR}:/media/movies
      - ${MOVIES_OVERFLOW_DIR}:/media/movies_overflow
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - media_network

  # Subtitle Management - Bazarr
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    ports:
      - "6767:6767"
    volumes:
      - ${CONFIG_DIR}/bazarr:/config
      - ${TV_DIR}:/media/tv
      - ${MOVIES_DIR}:/media/movies
      - ${MOVIES_OVERFLOW_DIR}:/media/movies_overflow
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - media_network

  # Music Server - Navidrome
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    ports:
      - "4533:4533"
    volumes:
      - ${CONFIG_DIR}/navidrome:/data
      - ${MUSIC_DIR}:/music:ro
    environment:
      - ND_SCANINTERVAL=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - TZ=${TZ}
    networks:
      - media_network

  # Request Management - Jellyseerr
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    ports:
      - "5055:5055"
    volumes:
      - ${CONFIG_DIR}/jellyseerr:/app/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - media_network

  # Indexer Proxy - Jackett
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    ports:
      - "9117:9117"
    volumes:
      - ${CONFIG_DIR}/jackett:/config
      - ${DOWNLOADS_DIR}:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - media_network

  # Indexer Management - Prowlarr
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - media_network

  # Optional: Monitoring and Analytics - Tautulli
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    ports:
      - "8181:8181"
    volumes:
      - ${CONFIG_DIR}/tautulli:/config
      - ${CONFIG_DIR}/jellyfin/log:/logs:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - media_network

networks:
  media_network:
    driver: bridge

volumes:
  jellyfin_config:
  qbittorrent_config:
  sonarr_config:
  radarr_config:
  bazarr_config:
  navidrome_config:
  jellyseerr_config:
  jackett_config:
  prowlarr_config:
  tautulli_config: 