version: '3.8'

services:
  # Media Server - Jellyfin
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - ./config/jellyfin:/config
      - /mnt/tv:/media/tv:ro
      - /mnt/movies:/media/movies:ro
      - /mnt/movies_overflow:/media/movies_overflow
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - media_network

  # Download Client - qBittorrent
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ./config/qbittorrent:/config
      - /mnt/downloads:/downloads
      - /mnt/tv:/media/tv
      - /mnt/movies:/media/movies
      - /mnt/movies_overflow:/media/movies_overflow
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    networks:
      - media_network

  # TV Show Management - Sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - ./config/sonarr:/config
      - /mnt/downloads:/downloads
      - /mnt/tv:/media/tv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - media_network

  # Movie Management - Radarr
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - ./config/radarr:/config
      - /mnt/downloads:/downloads
      - /mnt/movies:/media/movies
      - /mnt/movies_overflow:/media/movies_overflow
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - media_network

  # Subtitle Management - Bazarr
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    ports:
      - "6767:6767"
    volumes:
      - ./config/bazarr:/config
      - /mnt/tv:/media/tv
      - /mnt/movies:/media/movies
      - /mnt/movies_overflow:/media/movies_overflow
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - media_network

  # Music Server - Navidrome
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    ports:
      - "4533:4533"
    volumes:
      - ./config/navidrome:/data
      - /mnt/music:/music:ro
    environment:
      - ND_SCANINTERVAL=1h
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - TZ=Etc/UTC
    networks:
      - media_network

  # Request Management - Jellyseerr
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    ports:
      - "5055:5055"
    volumes:
      - ./config/jellyseerr:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - media_network

  # Indexer Proxy - Jackett
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    ports:
      - "9117:9117"
    volumes:
      - ./config/jackett:/config
      - /mnt/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - media_network

  # Optional: Monitoring and Analytics - Tautulli
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    ports:
      - "8181:8181"
    volumes:
      - ./config/tautulli:/config
      - ./config/jellyfin/log:/logs:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    networks:
      - media_network

networks:
  media_network:
    driver: bridge

volumes:
  jellyfin_config:
  qbittorrent_config:
  sonarr_config:
  radarr_config:
  bazarr_config:
  navidrome_config:
  jellyseerr_config:
  jackett_config:
  tautulli_config: 